#cloud-config
package_update: true
package_upgrade: false
packages: ["aspnetcore-runtime-8.0"]
write_files:
  - content: |
      [Unit]
      Description=Linker webservice

      [Service]
      WorkingDirectory=/home/ubuntu/linker
      ExecStart=/home/ubuntu/linker/linkr.web
      Restart=always
      # Restart service after 10 seconds if the dotnet service crashes:
      RestartSec=10
      KillSignal=SIGINT
      SyslogIdentifier=linker
      User=ubuntu
      Environment=ASPNETCORE_ENVIRONMENT=Production
      Environment=DOTNET_PRINT_TELEMETRY_MESSAGE=false
      Environment=ASPNETCORE_URLS=http://*:8080

      [Install]
      WantedBy=multi-user.target
    path: /etc/systemd/system/linker.service
runcmd:
  - mkdir -p /home/ubuntu/scripts
