name: Create Codespace

on:
  create:
    branches:
      - '*'

jobs:
  create-codespace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Codespace
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.CODESPACES_GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/codespaces \
          -d '{"ref":"${{ github.ref }}"}'
