# This workflow will build a golang project and run tests
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Deploy

on:
  push:
    branches: [ "main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download compiled file
      uses: actions/download-artifact@v3
      with:
        name: compiled
        path: .
    - name: Environment variables prod
      env:
        FEATURE_FLAG: ${{ secrets.FEATURE_FLAG }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWD: ${{ secrets.DB_PASSWD }}
      run: |
        chmod +x ./scripts/setup-project-linux.sh
        ./scripts/setup-project-linux.sh prod
        sed -i 's/{{DB_USERNAME}}/'"$DB_USERNAME"'/g' .env
        sed -i 's/{{DB_PASSWD}}/'"$DB_PASSWD"'/g' .env
    - name: Transfer files via SCP to prod
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY_JP }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 149.130.163.38 >> ~/.ssh/known_hosts
        scp -i ~/.ssh/id_rsa ./scripts/kill-current-process.sh ubuntu@149.130.163.38:~/scripts/kill-current-process.sh
        ssh -i ~/.ssh/id_rsa ubuntu@149.130.163.38 'chmod +x ~/scripts/kill-current-process.sh && ~/scripts/kill-current-process.sh && mkdir -p linker-prod'
        scp -i ~/.ssh/id_rsa api ubuntu@149.130.163.38:/home/ubuntu/linker-prod/url-shortener
        scp -i ~/.ssh/id_rsa .env ubuntu@149.130.163.38:/home/ubuntu/linker-prod/.env
        echo "archivos enviados"
        ssh -i ~/.ssh/id_rsa ubuntu@149.130.163.38 'nohup ~/linker-prod/url-shortener > ~/linker-prod/url-shortener.log 2>&1 &'
