# This workflow will build a golang project and run tests
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Validate Quality Code

on:
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Environment variables
      env:
        FEATURE_FLAG: ${{ secrets.FEATURE_FLAG }}
        DB_USERNAME: ${{ secrets.DEV_DB_USERNAME }}
        DB_PASSWD: ${{ secrets.DEV_DB_PASSWD }}
      run: |
        chmod +x ./scripts/setup-project-linux.sh
        ./scripts/setup-project-linux.sh dev
        sed -i 's/{{DB_USERNAME}}/'"$DB_USERNAME"'/g' .env
        sed -i 's/{{DB_PASSWD}}/'"$DB_PASSWD"'/g' .env
    - name: Uploading .env file
      uses: actions/upload-artifact@v3
      with:
        name: env-file
        path: .env

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: go build -v ./cmd/api
    - name: Upload compiled file
      uses: actions/upload-artifact@v3
      with:
        name: compiled
        path: api
  tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download .env file
      uses: actions/download-artifact@v3
      with:
        name: env-file
        path: .
    - name: Run Tests
      run: |
        cp .env ./cmd/api/application/.env
        go test -v ./...

  deploy:
    runs-on: ubuntu-latest
    needs: [build, tests]
    steps:
    - uses: actions/checkout@v4
    - name: Download .env file
      uses: actions/download-artifact@v3
      with:
        name: env-file
        path: .
    - name: Download compiled file
      uses: actions/download-artifact@v3
      with:
        name: compiled
        path: . 
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY_JP }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 149.130.183.133 >> ~/.ssh/known_hosts
    - name: Transfer files via SCP
      run: |
        scp -i ~/.ssh/id_rsa ./scripts/kill-current-process.sh ubuntu@149.130.183.133:~/scripts/kill-current-process.sh
        ssh -i ~/.ssh/id_rsa ubuntu@149.130.183.133 'chmod +x ~/scripts/kill-current-process.sh && ~/scripts/kill-current-process.sh && mkdir -p linker'
        scp -i ~/.ssh/id_rsa api ubuntu@149.130.183.133:/home/ubuntu/linker/url-shortener
        scp -i ~/.ssh/id_rsa .env ubuntu@149.130.183.133:/home/ubuntu/linker/.env
        echo "archivos enviados"
        ssh -i ~/.ssh/id_rsa ubuntu@149.130.183.133 'nohup ~/linker/url-shortener > ~/linker/url-shortener.log 2>&1 &'
    - name: E2E Tests
      run: |
        ssh -i ~/.ssh/id_rsa -N -L 8080:localhost:8080 ubuntu@149.130.183.133 -vvv &
        sleep 5 # Give SSH tunnel some time to establish
        response=$(curl -s localhost:8080/ping)
        if [ "$response" != "pong" ]; then
          echo "Validation failed: expected 'pong' but got '$response'"
          exit 1
        fi
        echo "Validation succeeded: received 'pong'"